version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: "03:00"
  target-branch: develop
  reviewers:
  - fr0zen
  assignees:
  - fr0zen
  ignore:
  - dependency-name: react-responsive-carousel
    versions:
    - 3.2.11
    - 3.2.12
    - 3.2.13
    - 3.2.14
    - 3.2.15
    - 3.2.16
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@fortawesome/free-solid-svg-icons"
    versions:
    - 5.15.2
